### ISSUE TITLE
Registration for user

### ISSUE THREAD

**Issue by priyankawebqua** [priyankawebqua/Kootam#1]
Profile image
a. choose from gallery (With cropping)
b. take a photo (With cropping)

User details
1. Name (4 letters min)
2. Mobile no (10 letters)
3.Email (email validation)
4.Gender (Male, female)
5.Dob (Age Between 10 to 90 Years)
6. Password (Between 5 to 20)
7. Reenter password (Match with above password)

If all the above conditions are true. Save details to user table, else show error .

![screenshot 49](https://cloud.githubusercontent.com/assets/20830825/17392042/452ed8e8-5a38-11e6-8996-c85b0700a0f4.png)

**Comment by amalsajuvarghese** [comment]
user registration completed
